steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/frontend:$COMMIT_SHA', './src/frontend']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/frontend:$COMMIT_SHA']

- name: 'gcr.io/gcp-runtimes/container-analysis'
  args: ['signed', 'build', 'gcr.io/$PROJECT_ID/frontend:$COMMIT_SHA']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: bash
  args:
    - '-c'
    - |
      git clone https://github.com/$_REPO_NAME.git
      cd $REPO_NAME/k8s-manifests
      sed -i "s|newTag:.*|newTag: '$COMMIT_SHA'|g" frontend-deployment.yaml
      git config --global user.email "cloudbuild@$PROJECT_ID.iam.gserviceaccount.com"
      git config --global user.name "Cloud Build"
      git commit -am "Update frontend to $COMMIT_SHA"
      git push origin main

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: bash
  args:
    - '-c'
    - |
      gcloud container clusters get-credentials $CLUSTER_NAME --region $_REGION
      kubectl apply -f k8s-manifests/